### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by GeorgeGkas-zz** [routerkeygen/thomsonDicGenerator#1]
Helo,
I wanted to ask how to compile the program? I work on Ubuntu distro 64bit and also have java jdk.  I don't use an ide.
I also wanted to ask, for what years this program generate keys. Only for 2011-2012 or from 2004-2012?
And what about the later years 2013 and 2014? Do we know the algorithm for that years?

Thank you for your time

**Comment by ruiaraujo** [comment]
The algorithm is known but it is different and it is not vulnerable. This is an Eclipse project so you should use it to import the project.
